resources:
  repositories:
  - repository: 'templates'
    type: 'git'
    name: 'ops\pipelines'
    ref: 'refs/heads/test'

variables:
  system.debug: true
  
stages:

- template: common/buildStage.yml@templates
  parameters:
    publishArtifacts: true
    artifactName: drop
    templateSpecificsDir: app1
    linuxAgentVmImagePool: 'ubuntu-latest'
    windowsAgentVmImagePool: 'windows-latest'
    sonarEndpoint: sonar1
    checkmarxEndpoint: checkmarx1
    checkmarxTeam: 'CxServer\SP\Company\xxx'
    buildStage:
      name: Build
  
- template: common/releaseStage.yml@templates
  parameters:
    templateSpecificsDir: app1
    linuxAgentVmImagePool: 'ubuntu-latest'
    windowsAgentVmImagePool: 'windows-latest'
    sonarEndpoint: sonar1
    checkmarxEndpoint: checkmarx1
    checkmarxTeam: 'CxServer\SP\Company\xxx'
    releaseStages:
  ###################### release develop branch ######################
    - name: Dev
      dependsOn: Build
      branchCond: 'refs/heads/develop'
    - name: QA
      dependsOn: Dev
      branchCond: 'refs/heads/develop'
  ###################### release master branch ######################
    - name: Stage
      dependsOn: Build
      branchCond: 'refs/heads/master'
    - name: Prod
      dependsOn: Stage
      branchCond: 'refs/heads/master'
