parameters:
  additionalVariables: {} # {__default__: {var1: val1, var2: val2, ...}}

stages:

- stage: ${{parameters.buildStage.name}}
  variables:
  - ${{ each varTmpl in parameters.buildStage.variables }}:
    - template: ../${{parameters.templateSpecificsDir}}/variables/${{varTmpl}}.yml
  - ${{ each varGroup in parameters.buildStage.variableGroups }}:
    - group: ${{varGroup}}
  - ${{ each pair in parameters.additionalVariables['__default__'] }}:
    - name:  ${{ pair.key }}
      value: ${{ pair.value }}
  jobs:
  - template: buildStageContent.yml
    parameters:
      ${{ insert }}: ${{parameters}}
