parameters:
  stageName: ''
  environment: ''
  logicalEnvironment: dev
  azureSub: ''
  webAppRG: ''
  webApp: ''
  slot: ''
  artifactName: 'drop'
  linuxAgentVmImagePool: 'ubuntu-latest'
  windowsAgentVmImagePool: 'VS2017-Win2016'
  additionalVariables: {} # {__default__: {var1: val1, var2: val2, ...}, environment1: {...}, environment2: {...} ...}
  downloadSteps:
  - download: current
    artifact: ${{parameters.artifactName}}

jobs:

- deployment: "${{parameters.stageName}}_Deployment"
  pool: 
    vmImage: ${{parameters.linuxAgentVmImagePool}}
  environment: ${{parameters.stageName}}
  variables:
    deploymentVar: deploymentValue -- $(Api.Url)
    ${{ each stageVariables in parameters.additionalVariables }}:
      ${{ if eq(stageVariables.key, parameters.stageName) }}:
        ${{insert}}: ${{ stageVariables.value }}
  strategy:
    runOnce:
      deploy:
        steps:
        - ${{ parameters.downloadSteps }}

        - template: snippet-deploy.yml
          parameters:
            azureSub: ${{parameters.azureSub}}
            webAppRG: ${{parameters.webAppRG}}-${{parameters.stageName}}-webapp
            webApp: ${{parameters.webApp}}-${{parameters.stageName}}
            slot: ${{parameters.slot}}

        - ${{ if eq(parameters.stageName, 'Dev') }}:
          - template: snippet-smoke-tests.yml

        - ${{ if eq(parameters.stageName, 'QA') }}:
          - template: snippet-functional-tests.yml

        - ${{ if eq(parameters.stageName, 'Stage') }}:
          - template: snippet-integration-tests.yml

        - ${{ if eq(parameters.stageName, 'Prod') }}:
          - template: snippet-additional-tests.yml
