parameters:
  stageName: ''
  environment: ''
  logicalEnvironment: dev
  webAppRG: ''
  webApp: ''
  azureSub: ''
  slot: 'production'
  linuxAgentVmImagePool: 'ubuntu-latest'
  windowsAgentVmImagePool: 'VS2017-Win2016'
  additionalVariables: {} # {__default__: {var1: val1, var2: val2, ...}, environment1: {...}, environment2: {...} ...}
  downloadSteps:
  - download: current
    artifact: drop

jobs:

- deployment: "${{parameters.stageName}}_Deployment"
  pool: 
    vmImage: ${{parameters.linuxAgentVmImagePool}}
  environment: ${{parameters.stageName}}
  variables:
    RGPrefix: demo1
    WebAppPrefix: demo1
    AzureSubscription: automagically-azure
    deploymentVar: deploymentValue -- $(Api.Url)
    ${{ each stageVariables in parameters.additionalVariables }}:
      ${{ if eq(stageVariables.key, parameters.stageName) }}:
        ${{insert}}: ${{ stageVariables.value }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: none

        - template: snippet-deploy.yml
          parameters:
            azureSub: $(AzureSubscription)
            webAppRG: $(RGPrefix)-${{parameters.stageName}}-webapp
            webApp: $(WebAppPrefix)-${{parameters.stageName}}
            slot: production

        - ${{ if eq(parameters.stageName, 'Dev') }}:
          - template: snippet-smoke-tests.yml

        - ${{ if eq(parameters.stageName, 'QA') }}:
          - template: snippet-functional-tests.yml

        - ${{ if eq(parameters.stageName, 'Stage') }}:
          - template: snippet-integration-tests.yml

        - ${{ if eq(parameters.stageName, 'Prod') }}:
          - template: snippet-additional-tests.yml
