parameters:
  linuxAgentPool:  'ubuntu-latest'
  windowsAgentVmImagePool: 'windows-latest'
  additionalVariables: {} # {__default__: {var1: val1, var2: val2, ...}, stageName1: {...}, stageName2: {...} ...}
  releaseStages:
  - name: Example
    dependsOn: AnotherStage
    branchCond: refs/heads/master
    variableGroups:
    - Variables_Example
    - AnotherVarGroup
    variables:
    - file1 # without .yml, searched in variables/
    - file2 # without .yml, searched in variables/

stages:

- ${{ each stage in parameters.releaseStages }}:
  - stage: ${{stage.name}}
    dependsOn: ${{stage.dependsOn}}
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], '${{stage.branchCond}}'))
    variables:
    - ${{ each varTmpl in stage.variables }}:
      - template: ../${{parameters.templateSpecificsDir}}/variables/${{varTmpl}}.yml
    - ${{ each varGroup in stage.variableGroups }}:
      - group: ${{varGroup}}
    - ${{ each pair in parameters.additionalVariables['__default__'] }}:
      - name:  ${{ pair.key }}
        value: ${{ pair.value }}
    jobs:
    - template: releaseStageContent.yml
      parameters:
        stageName: ${{stage.name}}
        azureSub: 'automagically-azure'
        webAppRG: 'demo1'
        webApp: 'demo1'
        slot: 'production'
        artifactName: 'drop'
        pool:
          vmImage: ${{parameters.windowsAgentVmImagePool}}
        additionalVariables: ${{parameters.additionalVariables}}
