parameters:
  environment: ''
  logicalEnvironment: dev
  webAppRG: ''
  webApp: ''
  azureSub: ''
  slot: 'production'
  linuxAgentVmImagePool: 'ubuntu-latest'
  windowsAgentVmImagePool: 'VS2017-Win2016'
  additionalVariables: {} # {__default__: {var1: val1, var2: val2, ...}, environment1: {...}, environment2: {...} ...}
  downloadSteps:
  - download: current
    artifact: drop

jobs:

- deployment: "${{parameters.environment}}_Deployment"
  pool: 
    vmImage: ${{parameters.linuxAgentVmImagePool}}
  environment: ${{parameters.environment}}
  variables:
    RGPrefix: demo1
    WebAppPrefix: demo1
    AzureSubscription: automagically-azure
    deploymentVar: deploymentValue -- $(Api.Url)
    ${{ each stageVariables in parameters.additionalVariables }}:
      ${{ if eq(stageVariables.key, parameters.environment) }}:
        ${{insert}}: ${{ stageVariables.value }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: none

        - template: snippet-deploy.yml
          parameters:
            environment: ${{parameters.environment}}
            logicalEnvironment: ${{parameters.environment}}
            slot: production
            webAppRG: $(RGPrefix)-${{parameters.environment}}-webapp
            webApp: $(WebAppPrefix)-${{parameters.environment}}
            azureSub: $(AzureSubscription)

        - ${{ if eq(parameters.environment, 'Dev') }}:
          - template: snippet-smoke-tests.yml

        - ${{ if eq(parameters.environment, 'QA') }}:
          - template: snippet-functional-tests.yml

        - ${{ if eq(parameters.environment, 'Stage') }}:
          - template: snippet-integration-tests.yml

        - ${{ if eq(parameters.environment, 'Prod') }}:
          - template: snippet-additional-tests.yml
